# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caa52bc7e8a734ca6a910b04a1617a75300ebd9ceab883e5764c069f02314b7af0c7c442c9017ac68f05b74ba0b16f65c3e1717d8b136b864883b6e5e23c14bc

test:
  secret_key_base: f8abb5338df4b5ac180e160dbf30f093d4d3553f76005f2fefe12762be2a976041d524f3a8eb810b3b301e56f3834d91c04fc15b117d2c464a510cc0a8a24468

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
